#!/bin/sh

bspc config border_width          1
bspc config window_gap            0
bspc config split_ratio           0.618
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           24
bspc config focus_follows_pointer true
bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#aaaaaa"

bspc monitor -d "α" "β" "γ" "δ" "ε"

bspc rule -a MPlayer  floating=on
bspc rule -a mpv  floating=on
