#!/bin/sh

bspc config border_width          1
bspc config window_gap            0
bspc config -m ^2 window_gap      0
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focus_by_distance     true
bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#aaaaaa"

bspc config split_ratio           0.618
bspc config -m ^1 top_padding     24
bspc config -m ^2 top_padding     0

bspc monitor -d "1" "2" "3" "4" "5"

bspc rule -a mpv floating=on
bspc rule -a Emacs split_ratio=0.5 monitor=^2
