#!/bin/sh

# Remove old/irrelevant files
rm *.pcf *.bdf.bak fonts.dir fonts.scale

# Create PCF fonts
for f in *.bdf; do
	bdftopcf -o "${f%\.*}.pcf" "$f"
done

# Create X font register files
mkfontdir
mkfontscale
xset fp rehash
