#!/bin/sh

bspc monitor -d I II III IV V

bspc config border_width          1
bspc config window_gap            0
bspc config split_ratio           0.618
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           26
bspc config focus_follows_pointer true
bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#aaaaaa"

bspc rule -a mplayer  floating=on
bspc rule -a skype    desktop=^4
bspc rule -a spotify  desktop=^5
bspc rule -a Chromium desktop=^1
